/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unab.edu.Vistas;

import javax.swing.JOptionPane;

/**
 *
 * @author AndresC
 */
public class FrmLoguin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLoguin
     */
    public FrmLoguin() {
        initComponents();
        this.setLocationRelativeTo(null);
        pwContra.setEchoChar('\u2022');
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnIzquierdo = new javax.swing.JPanel();
        lblEncabezado = new javax.swing.JLabel();
        lblCorroElec = new javax.swing.JLabel();
        txtCorreoElectronico = new javax.swing.JTextField();
        lblContra = new javax.swing.JLabel();
        pwContra = new javax.swing.JPasswordField();
        sepUsuario = new javax.swing.JSeparator();
        sepContra = new javax.swing.JSeparator();
        chbMostrarCarac = new javax.swing.JCheckBox();
        btnEntrar = new javax.swing.JButton();
        lblPiedeLogin = new javax.swing.JLabel();
        pnDerecho = new javax.swing.JPanel();
        lblCerrar = new javax.swing.JLabel();
        lblImagenPresentacion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.9F);
        setSize(new java.awt.Dimension(720, 470));

        pnIzquierdo.setBackground(new java.awt.Color(255, 255, 255));
        pnIzquierdo.setForeground(new java.awt.Color(255, 255, 255));

        lblEncabezado.setBackground(new java.awt.Color(255, 255, 255));
        lblEncabezado.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        lblEncabezado.setForeground(new java.awt.Color(0, 0, 0));
        lblEncabezado.setText("Inicio de Sesión");

        lblCorroElec.setBackground(new java.awt.Color(255, 255, 255));
        lblCorroElec.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblCorroElec.setForeground(new java.awt.Color(13, 94, 222));
        lblCorroElec.setText("Correo Electrónico:");

        txtCorreoElectronico.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreoElectronico.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtCorreoElectronico.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreoElectronico.setBorder(null);

        lblContra.setBackground(new java.awt.Color(255, 255, 255));
        lblContra.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblContra.setForeground(new java.awt.Color(13, 94, 222));
        lblContra.setText("Contraseña:");

        pwContra.setBackground(new java.awt.Color(255, 255, 255));
        pwContra.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        pwContra.setForeground(new java.awt.Color(0, 0, 0));
        pwContra.setBorder(null);

        sepUsuario.setBackground(new java.awt.Color(13, 94, 222));
        sepUsuario.setForeground(new java.awt.Color(13, 94, 222));

        sepContra.setBackground(new java.awt.Color(13, 94, 222));
        sepContra.setForeground(new java.awt.Color(13, 94, 222));

        chbMostrarCarac.setBackground(new java.awt.Color(255, 255, 255));
        chbMostrarCarac.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        chbMostrarCarac.setForeground(new java.awt.Color(13, 94, 222));
        chbMostrarCarac.setText("Mostrar Caracteres");
        chbMostrarCarac.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        chbMostrarCarac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbMostrarCaracActionPerformed(evt);
            }
        });

        btnEntrar.setBackground(new java.awt.Color(255, 255, 255));
        btnEntrar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/botonInicio.png"))); // NOI18N
        btnEntrar.setBorderPainted(false);
        btnEntrar.setFocusPainted(false);
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        lblPiedeLogin.setBackground(new java.awt.Color(255, 255, 255));
        lblPiedeLogin.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblPiedeLogin.setForeground(new java.awt.Color(255, 0, 0));
        lblPiedeLogin.setText("¡Aún no soy un usuario, Resgistrame!");
        lblPiedeLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPiedeLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnIzquierdoLayout = new javax.swing.GroupLayout(pnIzquierdo);
        pnIzquierdo.setLayout(pnIzquierdoLayout);
        pnIzquierdoLayout.setHorizontalGroup(
            pnIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnIzquierdoLayout.createSequentialGroup()
                .addGroup(pnIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnIzquierdoLayout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addGroup(pnIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sepContra, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblEncabezado)
                                .addComponent(lblCorroElec)
                                .addComponent(txtCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblContra)
                                .addComponent(pwContra, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sepUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnIzquierdoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(chbMostrarCarac)))
                    .addGroup(pnIzquierdoLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(lblPiedeLogin)))
                .addGap(51, 51, 51))
        );
        pnIzquierdoLayout.setVerticalGroup(
            pnIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnIzquierdoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblEncabezado)
                .addGap(62, 62, 62)
                .addComponent(lblCorroElec)
                .addGap(6, 6, 6)
                .addComponent(txtCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblContra)
                .addGap(6, 6, 6)
                .addComponent(pwContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepContra, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbMostrarCarac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEntrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(lblPiedeLogin)
                .addGap(24, 24, 24))
        );

        pnDerecho.setBackground(new java.awt.Color(13, 94, 222));

        lblCerrar.setBackground(new java.awt.Color(13, 94, 222));
        lblCerrar.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        lblCerrar.setToolTipText("");
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });

        lblImagenPresentacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/graduation.png"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(13, 94, 222));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¡Te damos la bienvenida!");

        javax.swing.GroupLayout pnDerechoLayout = new javax.swing.GroupLayout(pnDerecho);
        pnDerecho.setLayout(pnDerechoLayout);
        pnDerechoLayout.setHorizontalGroup(
            pnDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDerechoLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(pnDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDerechoLayout.createSequentialGroup()
                        .addComponent(lblCerrar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDerechoLayout.createSequentialGroup()
                        .addGroup(pnDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblImagenPresentacion)
                            .addComponent(jLabel1))
                        .addGap(41, 41, 41))))
        );
        pnDerechoLayout.setVerticalGroup(
            pnDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDerechoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCerrar)
                .addGap(78, 78, 78)
                .addComponent(lblImagenPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnIzquierdo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pnDerecho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnIzquierdo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnDerecho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed

        if (txtCorreoElectronico.getText().isEmpty() || pwContra.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "¡Por favor introduzca todos los datos para iniciar sesión!");
        } else {
//            FrmInicioAlumno startAlumno = new FrmInicioAlumno();
//            startAlumno.setVisible(true);
//            this.dispose();

            JOptionPane.showMessageDialog(null, "Bienvenido " + txtCorreoElectronico.getText() + ", usted acaba de iniciar sesión.");
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void chbMostrarCaracActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbMostrarCaracActionPerformed

        if (chbMostrarCarac.isSelected()) {
            pwContra.setEchoChar((char) 0);
        } else {
            pwContra.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_chbMostrarCaracActionPerformed

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked

        String botones[] = {"Salir", "Cancelar"};
        int opcion = JOptionPane.showOptionDialog(this, "¿Estás seguro que quieres salir?", "Confirmar", 0, 0, null, botones, this);

        if (opcion == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else if (opcion == JOptionPane.NO_OPTION) {
            System.out.println("¡Cancelado!");
        }
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblPiedeLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPiedeLoginMouseClicked
       
        FrmRegistroPersona nuevoR = new FrmRegistroPersona();
        nuevoR.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblPiedeLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLoguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLoguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLoguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLoguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLoguin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JCheckBox chbMostrarCarac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblContra;
    private javax.swing.JLabel lblCorroElec;
    private javax.swing.JLabel lblEncabezado;
    private javax.swing.JLabel lblImagenPresentacion;
    private javax.swing.JLabel lblPiedeLogin;
    private javax.swing.JPanel pnDerecho;
    private javax.swing.JPanel pnIzquierdo;
    private javax.swing.JPasswordField pwContra;
    private javax.swing.JSeparator sepContra;
    private javax.swing.JSeparator sepUsuario;
    private javax.swing.JTextField txtCorreoElectronico;
    // End of variables declaration//GEN-END:variables
}
