/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unab.edu.Vistas.Docente;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CruzCalles
 */
public class PnStrarMateriasDocente extends javax.swing.JPanel {

    /**
     * Creates new form PnStrarMateriasDocente
     */
    public PnStrarMateriasDocente() {
        initComponents();
        setBackground(new Color(0,0,0,0));
        
        tb_Materias_Docente.getTableHeader().setFont(new Font("Century Gothic", Font.PLAIN, 11));
        tb_Materias_Docente.getTableHeader().setOpaque(false);
        tb_Materias_Docente.setBackground(new Color(0,201,215));
        tb_Materias_Docente.setForeground(new Color(255,255,255));
        tb_Materias_Docente.setRowHeight(25);
        
        tb_Materias_Asignadas.getTableHeader().setFont(new Font("Century Gothic", Font.PLAIN, 11));
        tb_Materias_Asignadas.getTableHeader().setOpaque(false);
        tb_Materias_Asignadas.setBackground(new Color(0,201,215));
        tb_Materias_Asignadas.setForeground(new Color(255,255,255));
        tb_Materias_Asignadas.setRowHeight(25);
        
    }

     public void limpiarTabla(JTable Tabla) {
        try {
            DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();
            int filas = Tabla.getRowCount();
            for (int i = 0; filas > i; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnInscribir = new com.unab.edu.Otros.Boton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblActulizar = new javax.swing.JLabel();
        btnInscribir1 = new com.unab.edu.Otros.Boton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Materias_Docente = new javax.swing.JTable();
        txtNombres = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnGuardar = new com.unab.edu.Otros.Boton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_Materias_Asignadas = new javax.swing.JTable();
        cbGradoAcademico = new javax.swing.JComboBox<>();

        jLabel3.setBackground(new java.awt.Color(68, 130, 195));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Materia Seleccionada:");

        btnInscribir.setText("      Inscribir");
        btnInscribir.setBorderPainted(false);
        btnInscribir.setFocusPainted(false);
        btnInscribir.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        btnInscribir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jPanel1.setBackground(new java.awt.Color(68, 130, 195));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 590));

        jLabel1.setBackground(new java.awt.Color(68, 130, 195));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¡Bienvenido a tu sección de Materias!");

        lblActulizar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblActulizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/browser.png"))); // NOI18N
        lblActulizar.setText("Actualizar");

        btnInscribir1.setText("      Inscribir");
        btnInscribir1.setBorderPainted(false);
        btnInscribir1.setFocusPainted(false);
        btnInscribir1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        btnInscribir1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        tb_Materias_Docente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CÓDIGO", "NOMBRE MATERIA"
            }
        ));
        tb_Materias_Docente.setFocusable(false);
        tb_Materias_Docente.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tb_Materias_Docente.setRowHeight(25);
        tb_Materias_Docente.setSelectionBackground(new java.awt.Color(48, 218, 174));
        tb_Materias_Docente.setShowVerticalLines(false);
        tb_Materias_Docente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_Materias_DocenteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_Materias_Docente);

        txtNombres.setBackground(new java.awt.Color(68, 130, 195));
        txtNombres.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtNombres.setForeground(new java.awt.Color(255, 255, 255));
        txtNombres.setBorder(null);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("¿No encuentras la materia?, Registrala:");

        btnGuardar.setText("  Guardar");
        btnGuardar.setBorderPainted(false);
        btnGuardar.setFocusPainted(false);
        btnGuardar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        tb_Materias_Asignadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CÓDIGO", "MATERIA SELECCIONADA"
            }
        ));
        tb_Materias_Asignadas.setFocusable(false);
        tb_Materias_Asignadas.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tb_Materias_Asignadas.setRowHeight(25);
        tb_Materias_Asignadas.setSelectionBackground(new java.awt.Color(48, 218, 174));
        tb_Materias_Asignadas.setShowVerticalLines(false);
        tb_Materias_Asignadas.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tb_Materias_Asignadas);

        cbGradoAcademico.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cbGradoAcademico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grado academico", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblActulizar)
                        .addGap(11, 11, 11)))
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnInscribir1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(cbGradoAcademico, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(128, 128, 128)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(lblActulizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbGradoAcademico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnInscribir1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    String TITULOS1[] = {"CODIGO", "MATERIA SELECCIONADA"};
    DefaultTableModel ModeloTabla_MatSele = new DefaultTableModel(null, TITULOS1);
    
    private void tb_Materias_DocenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_Materias_DocenteMouseClicked
        
         //Acá estamos obteniendo la fila que el usuario seleccionó.
        int filas = tb_Materias_Docente.getSelectedRow();
        //Asignamos todos los campos de la tabla.
        String ID = String.valueOf(tb_Materias_Docente.getValueAt(filas, 0));
        String Nombre = String.valueOf(tb_Materias_Docente.getValueAt(filas, 1));
        //Pasamos los datos para la tabla a inscribir.
        String Filas[] = new String[3];
        Filas[0] = ID;
        Filas[1] = Nombre;
        
         for (int i = 0; i < tb_Materias_Asignadas.getRowCount(); i++) {

            if (tb_Materias_Asignadas.getValueAt(i, 0) == ID) {
                JOptionPane.showMessageDialog(null, "¡Ya ha seleccionado esta materia!");
                ModeloTabla_MatSele.removeRow(i);
                //no se de donde sale este atributo O de donde lo obtienen en el frm de estudiante materia.
            }
        }

        ModeloTabla_MatSele.addRow(Filas);
        tb_Materias_Asignadas.setModel(ModeloTabla_MatSele);
    }//GEN-LAST:event_tb_Materias_DocenteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.unab.edu.Otros.Boton btnGuardar;
    private com.unab.edu.Otros.Boton btnInscribir;
    private com.unab.edu.Otros.Boton btnInscribir1;
    private javax.swing.JComboBox<String> cbGradoAcademico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblActulizar;
    private javax.swing.JTable tb_Materias_Asignadas;
    private javax.swing.JTable tb_Materias_Docente;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
